# Generated by Django 5.1 on 2024-08-24 07:07

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255, validators=[core.validators.validate_password])),
                ('address', models.CharField(max_length=255, validators=[core.validators.validate_address])),
                ('phone_number', models.CharField(max_length=20, validators=[core.validators.validate_phone_number_with_country])),
                ('profile_picture', models.ImageField(upload_to='profile_pics/')),
            ],
        ),
    ]
