# Generated by Django 5.1 on 2024-08-25 09:19

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_management', '0003_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, validators=[core.validators.validate_phone_number_with_country]),
        ),
    ]
